### ISSUE TITLE
[Proposal] Text messages should use "message" rather than "sms_message"

### ISSUE THREAD

**Issue by andyfleming** [aloha/laravel4-twilio#19]
The `Twilio::message(...)` function should probably use the new message endpoint/tool rather than the SMS one. It supports longer messages, etc. I'm not sure if there are any downsides.

See [src/Aloha/Twilio/Twilio.php at Line 16](https://github.com/aloha/laravel4-twilio/blob/master/src/Aloha/Twilio/Twilio.php#L16)

```
return $twilio->account->sms_messages->create(
```

would be changed to

```
 return $twilio->account->messages->sendMessage(
```

I'm happy to make the change. I just wanted to get feedback first before making it. There is potential it could be a breaking change.

**Comment by hannesvdvreken** [comment]
This can be closed.
