### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by nitesh35103** [aloha/laravel4-twilio#23]
Hello,

Thanks for sharing this library.
I following the steps and update the config file with the token and sid accordingly. 

But I am getting below err:
Services_Twilio_TinyHttpException (E_UNKNOWN)
SSL certificate problem: self signed certificate in certificate chain
Open: C:\wamp\www\hello\vendor\twilio\sdk\Services\Twilio\TinyHttp.php
            }
            curl_close($curl);
            if (isset($buf) && is_resource($buf)) {
                fclose($buf);
            }
            return array($status, $headers, $body);
          } else {
              throw new Services_Twilio_TinyHttpException(curl_error($curl));
          }
        } else throw new Services_Twilio_TinyHttpException(curl_error($curl));

Can you please suggest, what I am missing.

Thanks 
Nitesh

**Comment by hannesvdvreken** [comment]
I'm surprised twilio has ssl certificate problems.

Since PR #21 you can disable ssl verification. This will be available in the next release.

**Comment by broy5209** [comment]
When the next version release? (sorry i'm currently rushing to complete my project :D)

**Comment by hannesvdvreken** [comment]
You can upgrade to the latest version at your own risk (it's untested) using `composer require aloha/twilio:dev-master#2c34c2b0` to lock the commit hash to `2c34c2b0`.
